# Generated by Django 4.0.4 on 2022-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_project_link_projectlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='background',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/portfolio/thumbs/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/portfolio/thumbs/'),
        ),
    ]
