# Generated by Django 4.0.4 on 2022-07-09 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_category_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.category'),
        ),
    ]
